---
# tasks wordpress

- name: install wp-cli  
  get_url: 
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0755
  become: yes

- name: mkdir /var/www/wordpress
  file:
    path: /var/www/wordpress
    state: directory
    mode: 0755

- name: download wordpress
  command: wp core download --allow-root
  args:
    chdir: /var/www/wordpress
  become: yes

- name: config wp-config.php
  command: wp config create --dbname={{ wp_mysql_db }} --dbuser={{ wp_mysql_user }} --dbpass={{ wp_mysql_password }} --allow-root
  args:
    chdir: /var/www/wordpress
  become: yes

- name: install wordpress
  command: wp core install --url={{ site_url }} --title="{{ site_title }}" --admin_user={{ site_admin_user }} --admin_password={{ site_admin_password }} --admin_email={{ site_admin_email }} --allow-root
  args:
    chdir: /var/www/wordpress
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache