---
# оставил этот таск для себя(для истории), это первая версия деплоя вордпресса, до того как нашел wp-cli
# tasks wordpress

- name: Download WordPress  
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress  
  unarchive: 
    src: /tmp/wordpress.tar.gz 
    dest: /var/www/ 
    remote_src: yes
  #become: yes

- name: Update default Apache site
  become: yes
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php 
  args:
    creates: /var/www/wordpress/wp-config.php
  become: yes

- name: Update WordPress config file
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
  become: yes

- name: get salt for wp-config
  uri:
    url: "https://api.wordpress.org/secret-key/1.1/salt/"
    return_content: yes
    method: GET
  register: salt


- name: insert salt in wp-config
  lineinfile:
    path: /var/www/wordpress/wp-config.php
    regexp: "put your unique phrase here"
    #insertafter: "put your unique phrase here"
    line: "{{ salt.content }}"