---
# tasks install LAMP 

- name: add repo with php7
  apt_repository:
    repo: ppa:ondrej/php

- name: Install required software
  apt: name={{ item }} state=present update_cache=true
  become: yes
  loop:
    - apache2
    - mysql-server
    - php7.2-mysql
    - php7.2
    - libapache2-mod-php7.2
    - php7.2-gd